// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public struct Article
{
	public int articleID;
	public float preis;

	public Article(int id, float preis)
	{
		articleID = id;
		this.preis = preis;
	}

}


